name: GitHub Actions Demo

on:
  push:
   branches:
    - main
    - 'releases/**'
  pull_request:
   types:
    - opened
   branches:
    - '*feature'

jobs:
 build-job:
  runs-on: ubuntu-latest
  steps:
   - run: echo "Hello Word"
   - run: echo "Hello Word 2"
   - run: echo "Hello Word 3"